"""Plot policy-solver scenarios generated by generate_policy_scenarios.jl."""

from __future__ import annotations

import csv
import os
from collections import defaultdict
from pathlib import Path

PLOT_DIR = Path("output/new_CES_plots")
MPLCONFIG_DIR = PLOT_DIR / "mplconfig"
MPLCONFIG_DIR.mkdir(parents=True, exist_ok=True)
os.environ.setdefault("MPLCONFIGDIR", str(MPLCONFIG_DIR.resolve()))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


DATA_DIR = Path("output/new_CES_plots/data")

PLOT_SPECS = [
    ("e_policy", "Parental investment e"),
    ("l_policy", "Labor l"),
]

FAMILY_TITLES = {
    "parent_human_capital": "Varying Parent Human Capital",
    "parent_human_capital_complements": "Varying Parent Human Capital, rho = -0.40",
    "public_input": "Varying Public Input",
    "public_input_complements": "Varying Public Input, rho = -0.40",
    "rho": "Varying Perceived Substitutability",
}


def read_rows(path: Path) -> list[dict[str, str]]:
    with path.open(newline="") as f:
        return list(csv.DictReader(f))


def to_float(row: dict[str, str], key: str) -> float:
    return float(row[key])


def plot_family(path: Path) -> Path:
    rows = read_rows(path)
    by_period_scenario: dict[tuple[int, str], list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        by_period_scenario[(int(row["period"]), row["scenario"])].append(row)

    periods = sorted({int(row["period"]) for row in rows})
    fig, axes = plt.subplots(len(PLOT_SPECS), len(periods), figsize=(15, 7), sharex=True)

    for row_idx, (policy_key, label) in enumerate(PLOT_SPECS):
        for col_idx, period in enumerate(periods):
            ax = axes[row_idx][col_idx]
            scenarios = sorted(
                scenario
                for period_key, scenario in by_period_scenario
                if period_key == period
            )
            for scenario in scenarios:
                scenario_rows = by_period_scenario[(period, scenario)]
                scenario_rows.sort(key=lambda r: to_float(r, "hc"))
                x = [to_float(row, "hc") for row in scenario_rows]
                y = [to_float(row, policy_key) for row in scenario_rows]
                ax.plot(x, y, linewidth=2, label=scenario)

            ax.set_title(f"Period {period}: {label}")
            ax.set_xlabel("Current child human capital")
            ax.grid(True, alpha=0.25)

    axes[0][0].legend(frameon=False)
    fig.suptitle(FAMILY_TITLES.get(path.stem, path.stem), fontsize=15)
    fig.tight_layout()

    PLOT_DIR.mkdir(parents=True, exist_ok=True)
    output = PLOT_DIR / f"{path.stem}_labor_investment_all_periods.png"
    fig.savefig(output, dpi=160)
    plt.close(fig)
    return output


def main() -> None:
    csv_paths = sorted(DATA_DIR.glob("*.csv"))
    if not csv_paths:
        raise FileNotFoundError(
            f"No CSV files found in {DATA_DIR}. Run julia generate_policy_scenarios.jl first."
        )

    for path in csv_paths:
        output = plot_family(path)
        print(f"wrote {output}")


if __name__ == "__main__":
    main()
